### ISSUE TITLE
It does not work. 

### ISSUE THREAD

**Issue by afsungur** [imamathwiz/atom-hide-files#3]
I just installed the plugin to the Atom ( 0.162.0 ). 
When I try to hide folder or file it does not do anything.

**Comment by Digital-Thor** [comment]
I'm in Windows 7 and having the same problem.  Attempted right-click as well as Shift-Control-H.  (Good idea for a package though.)

**Comment by imamathwiz** [comment]
Sorry this took so long to fix.

@Digital-Thor If you can do me a favor and double check to make sure it works on Windows, that would be much appreciated.

**Comment by Digital-Thor** [comment]
@imamathwiz hiding files and folders is working now.  I tested both cases (in Windows 7 and Ubuntu 14).  Since you like math, QED and thank you! 

I also tested unhiding with `Shift-Control-U`.  That worked in Windows, but not Ubuntu.  I was able to clear in Ubuntu using the command palette though.  Thanks again!
